services:
  nifi:
    image: apache/nifi:1.25.0
    container_name: nifi
    ports:
      - "8080:8080"
    environment:
      - NIFI_WEB_HTTP_PORT=8080
      - NIFI_JVM_HEAP_INIT=1g
      - NIFI_JVM_HEAP_MAX=2g
    mem_limit: 2.5g
    volumes:
      - nifi_data:/opt/nifi/nifi-current/conf
      - ./data:/opt/nifi/data

  spark-master:
    image: apache/spark:3.5.3
    container_name: spark-master
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.master.Master
    ports:
      - "8081:8080"   # UI Spark master (port different de NiFi)
      - "7077:7077"
    mem_limit: 2g
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  spark-worker:
    image: apache/spark:3.5.3
    container_name: spark-worker
    command: /opt/spark/bin/spark-class org.apache.spark.deploy.worker.Worker spark://spark-master:7077
    depends_on:
      - spark-master
    environment:
      - SPARK_WORKER_MEMORY=2g
      - SPARK_WORKER_CORES=2
    mem_limit: 2.5g
    volumes:
      - ./data:/data
      - ./scripts:/scripts

  hive:
    image: apache/hive:4.0.0
    container_name: hive
    environment:
      - SERVICE_NAME=hiveserver2
    ports:
      - "10000:10000"   # HiveServer2 (JDBC/Beeline)
      - "10002:10002"   # Hive Web UI
    mem_limit: 4g
    volumes:
      - ./data:/data
      - hive_warehouse:/opt/hive/data/warehouse

  airflow:
    build:
      context: .
      dockerfile: Dockerfile.airflow
    container_name: airflow
    user: root
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=false
      - AIRFLOW__WEBSERVER__WORKERS=2
      - AIRFLOW__WEBSERVER__WEB_SERVER_MASTER_TIMEOUT=300
      - AIRFLOW__WEBSERVER__WEB_SERVER_WORKER_TIMEOUT=300
    ports:
      - "8082:8080"
    mem_limit: 3g
    volumes:
      - ./dags:/opt/airflow/dags
      - /var/run/docker.sock:/var/run/docker.sock
    command: standalone

  hue:
    image: gethue/hue:latest
    container_name: hue
    ports:
      - "8888:8888"
    mem_limit: 2g
    volumes:
      - ./data:/data

volumes:
  nifi_data:
  hive_warehouse: